"""Pydantic data schemas for CloudSentry state and telemetry representations.
"""

from __future__ import annotations
from typing import List, Optional, Literal, Dict, Any, Union
from pydantic import BaseModel, Field


class MetricPoint(BaseModel):
    """Represents a single point of time-series telemetry for a microservice."""
    timestamp: Union[str, float, int] = Field(..., description="Timestamp or sequence index of telemetry metric")
    service_name: str = Field(..., description="Target microservice identifier")
    cpu_usage_pct: float = Field(..., ge=0.0, description="CPU utilization percentage (0-100+)")
    memory_usage_mb: float = Field(..., ge=0.0, description="Memory consumption in megabytes")
    error_rate_pct: float = Field(..., ge=0.0, le=100.0, description="HTTP/gRPC error rate percentage (0-100)")
    p99_latency_ms: float = Field(..., ge=0.0, description="P99 latency in milliseconds")


class AnomalyReport(BaseModel):
    """Detailed anomaly diagnostic report generated by the telemetry detection engine."""
    service_name: str = Field(..., description="Name of the service assessed")
    anomaly_detected: bool = Field(..., description="Whether an anomalous pattern was identified")
    trigger_metric: Optional[str] = Field(None, description="Primary metric triggering anomaly detection")
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        "LOW", description="Assessed impact severity level"
    )
    summary: str = Field(..., description="Human and agent readable summary of findings")
    anomaly_score: Optional[float] = Field(None, description="Statistical or model anomaly score")


class RootCauseAnalysis(BaseModel):
    """Root Cause Analysis (RCA) correlation output isolating the failure mode."""
    culprit_service: str = Field(..., description="Service identified as root culprit")
    primary_failure_mode: Literal["OOM_KILL", "CPU_THROTTLING", "LATENCY_SPIKE"] = Field(
        ..., description="Classified failure mode"
    )
    evidence_logs: List[str] = Field(
        default_factory=list, description="Extracted telemetry logs and diagnostic observations"
    )
    confidence_score: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0"
    )


class RemediationPatch(BaseModel):
    """Remediation patch payload containing synthesized Kubernetes or Terraform diffs."""
    target_manifest: str = Field(..., description="Path or target manifest name to patch")
    patch_type: Literal["KUBERNETES_YAML", "TERRAFORM"] = Field(
        "KUBERNETES_YAML", description="Infrastructure declaration format"
    )
    diff_content: str = Field(..., description="Unified diff or complete corrected YAML content")
    reasoning: str = Field(..., description="Agent reasoning explaining why this patch fixes the incident")
    updated_manifest: Optional[str] = Field(None, description="Complete sanitized and patched manifest")


class ValidationResult(BaseModel):
    """Deterministic validation output from policy validator and YAML linter."""
    is_valid: bool = Field(..., description="True if manifest satisfies all linter and security rules")
    linter_errors: List[str] = Field(default_factory=list, description="YAML syntax or schema errors")
    policy_violations: List[str] = Field(
        default_factory=list, description="Security/FinOps policy violations (e.g., missing limits)"
    )
    retry_count: int = Field(0, ge=0, description="Current retry iteration count for agent self-correction")


class CloudSentryState(BaseModel):
    """Master state model tracking the end-to-end multi-agent remediation loop."""
    metrics: List[MetricPoint] = Field(default_factory=list, description="Ingested telemetry metrics")
    anomalies: List[AnomalyReport] = Field(default_factory=list, description="Detected anomalies across services")
    rca: Optional[RootCauseAnalysis] = Field(None, description="Root cause analysis result")
    patch: Optional[RemediationPatch] = Field(None, description="Current remediation patch candidate")
    validation: Optional[ValidationResult] = Field(None, description="Validation result of the patch candidate")
    iteration_count: int = Field(0, description="Number of remediation/validation loop attempts")
    status: Literal["INGESTING", "ANALYZING", "PATCHING", "VALIDATING", "REMEDIATED", "FAILED"] = Field(
        "INGESTING", description="Current lifecycle state of the incident response"
    )
    history_logs: List[str] = Field(default_factory=list, description="Audit trail of agent actions and decisions")

    def log(self, message: str) -> None:
        """Appends a timestamped log to the audit history."""
        self.history_logs.append(message)
